import { defineConfig } from 'oxlint';

export default defineConfig({
    categories: {
        correctness: 'off',
        perf: 'warn',
        style: 'warn',
    },

    env: {
        builtin: true,
    },

    ignorePatterns: [
        'node_modules',
        'dist',
        '**/*.js',
        '**/*.d.ts',
        '*.config*.ts',
        'infra',
        'migrations',
    ],

    options: {
        typeAware: true,
    },

    overrides: [
        {
            files: ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.cts'],
            rules: {
                'constructor-super': 'off',
                'getter-return': 'off',
                'no-class-assign': 'off',
                'no-const-assign': 'off',
                'no-dupe-class-members': 'off',
                'no-dupe-keys': 'off',
                'no-func-assign': 'off',
                'no-import-assign': 'off',
                'no-new-native-nonconstructor': 'off',
                'no-obj-calls': 'off',
                'no-redeclare': 'off',
                'no-setter-return': 'off',
                'no-this-before-super': 'off',
                'no-unreachable': 'off',
                'no-unsafe-negation': 'off',
                'no-with': 'off',
            },
        },
        {
            files: [
                '**/*.controller.ts',
                '**/*.service.ts',
                '**/*.module.ts',
                '**/*.guard.ts',
                '**/*.interceptor.ts',
                '**/*.pipe.ts',
                '**/*.filter.ts',
                '**/*.middleware.ts',
                '**/*.resolver.ts',
                '**/*.decorator.ts',
                '**/*.exception.ts',
            ],
            rules: {
                'typescript/consistent-type-imports': 'off',
                'new-cap': 'off',
                'typescript/parameter-properties': 'off',
            },
        },
        {
            files: ['**/*.spec.ts', '**/*.test.ts', '**/test/**/*.ts', '**/e2e/**/*.ts'],
            rules: {
                'no-magic-numbers': 'off',
                'init-declarations': 'off',
            },
        },
        {
            files: ['**/main.ts', '**/index.ts', '**/cli.ts'],
            rules: {
                'func-style': 'off',
                'no-magic-numbers': 'off',
            },
        },
    ],

    plugins: ['typescript', 'unicorn', 'jsdoc', 'node'],

    rules: {
        'constructor-super': 'error',
        'for-direction': 'error',
        'getter-return': 'error',
        'no-async-promise-executor': 'error',
        'no-case-declarations': 'error',
        'no-class-assign': 'error',
        'no-compare-neg-zero': 'error',
        'no-cond-assign': 'error',
        'no-const-assign': 'error',
        'no-constant-binary-expression': 'error',
        'no-constant-condition': 'error',
        'no-control-regex': 'error',
        'no-debugger': 'error',
        'no-delete-var': 'error',
        'no-dupe-class-members': 'error',
        'no-dupe-else-if': 'error',
        'no-dupe-keys': 'error',
        'no-duplicate-case': 'error',
        'no-empty': 'error',
        'no-empty-character-class': 'error',
        'no-empty-pattern': 'error',
        'no-empty-static-block': 'error',
        'no-ex-assign': 'error',
        'no-extra-boolean-cast': 'error',
        'no-fallthrough': 'error',
        'no-func-assign': 'error',
        'no-global-assign': 'error',
        'no-import-assign': 'error',
        'no-invalid-regexp': 'error',
        'no-irregular-whitespace': 'error',
        'no-loss-of-precision': 'error',
        'no-misleading-character-class': 'error',
        'no-new-native-nonconstructor': 'error',
        'no-nonoctal-decimal-escape': 'error',
        'no-obj-calls': 'error',
        'no-prototype-builtins': 'error',
        'no-redeclare': 'error',
        'no-regex-spaces': 'error',
        'no-self-assign': 'error',
        'no-setter-return': 'error',
        'no-shadow-restricted-names': 'error',
        'no-sparse-arrays': 'error',
        'no-this-before-super': 'error',
        'no-unassigned-vars': 'error',
        'no-unexpected-multiline': 'error',
        'no-unreachable': 'error',
        'no-unsafe-finally': 'error',
        'no-unsafe-negation': 'error',
        'no-unsafe-optional-chaining': 'error',
        'no-unused-labels': 'error',
        'no-unused-private-class-members': 'error',
        'no-useless-backreference': 'error',
        'no-useless-catch': 'error',
        'no-useless-escape': 'error',
        'no-with': 'error',
        'preserve-caught-error': 'error',
        'require-yield': 'error',
        'use-isnan': 'error',
        'valid-typeof': 'error',
        'no-array-constructor': 'error',
        'no-unused-expressions': 'error',
        'no-duplicate-imports': 'error',
        'no-console': [
            'warn',
            {
                allow: ['warn', 'error'],
            },
        ],
        'no-shadow': 'error',
        'no-param-reassign': 'warn',
        'no-promise-executor-return': 'error',
        'no-await-in-loop': 'warn',
        'no-useless-return': 'warn',
        eqeqeq: ['error', 'always'],
        curly: ['error', 'all'],
        'no-var': 'error',
        'prefer-const': 'error',
        'prefer-template': 'error',
        'object-shorthand': ['error', 'always'],
        'arrow-body-style': ['error', 'as-needed'],
        'prefer-arrow-callback': 'warn',
        'prefer-destructuring': 'warn',

        'typescript/ban-ts-comment': 'error',

        'typescript/no-duplicate-enum-values': 'error',
        'typescript/no-empty-object-type': 'error',
        'typescript/no-explicit-any': 'warn',
        'typescript/no-extra-non-null-assertion': 'error',
        'typescript/no-misused-new': 'error',
        'typescript/no-namespace': 'error',
        'typescript/no-non-null-assertion': 'warn',
        'typescript/no-non-null-asserted-optional-chain': 'error',
        'typescript/no-require-imports': 'error',
        'typescript/no-this-alias': 'error',
        'typescript/no-unnecessary-type-constraint': 'error',
        'typescript/no-unsafe-declaration-merging': 'error',
        'typescript/no-unsafe-function-type': 'error',
        'typescript/no-wrapper-object-types': 'error',

        'typescript/prefer-as-const': 'error',
        'typescript/prefer-for-of': 'warn',
        'typescript/prefer-function-type': 'warn',
        'typescript/prefer-includes': 'warn',
        'typescript/prefer-namespace-keyword': 'error',
        'typescript/prefer-optional-chain': 'warn',
        'typescript/prefer-readonly': 'warn',

        'typescript/triple-slash-reference': 'error',

        'typescript/consistent-type-imports': [
            'error',
            {
                disallowTypeAnnotations: false,
                fixStyle: 'separate-type-imports',
                prefer: 'type-imports',
            },
        ],

        'typescript/no-floating-promises': 'error',
        'typescript/await-thenable': 'error',

        'unicorn/filename-case': [
            'error',
            {
                case: 'kebabCase',
                ignore: ['index.ts', String.raw`\.d\.ts$`],
            },
        ],

        'unicorn/prefer-node-protocol': 'error',
        'unicorn/no-array-method-this-argument': 'warn',
        'unicorn/prefer-structured-clone': 'error',
        'unicorn/no-useless-undefined': 'error',
        'unicorn/prefer-export-from': 'error',
        'unicorn/prefer-spread': 'warn',
        'unicorn/no-array-reduce': 'warn',

        'jsdoc/require-param-type': 'error',
        'jsdoc/require-returns-type': 'error',

        'no-restricted-properties': [
            'error',
            {
                message: 'Используйте slice/spread вместо pop',
                object: 'Array',
                property: 'pop',
            },
            {
                message: 'Используйте filter/slice вместо splice',
                object: 'Array',
                property: 'splice',
            },
            {
                message: 'Используйте spread оператор: {...obj, newProp} вместо Object.assign',
                object: 'Object',
                property: 'assign',
            },
        ],
    },
});
