export const AuthErrorCodes = {
    INVALID_CREDENTIALS: 'AUTH.INVALID_CREDENTIALS',
    INVALID_CODE: 'AUTH.INVALID_CODE',
    CODE_ALREADY_SENT: 'AUTH.CODE_ALREADY_SENT',
    SESSION_EXPIRED: 'AUTH.SESSION_EXPIRED',
    SIGNOUT_FAILED: 'AUTH.SIGNOUT_FAILED',
    STRATEGY_NOT_FOUND: 'AUTH.STRATEGY_NOT_FOUND',
    SESSION_NOT_FOUND: 'AUTH.SESSION_NOT_FOUND',
    SESSION_REVOKED: 'AUTH.SESSION_REVOKED',
    TOKEN_INVALID: 'AUTH.TOKEN_INVALID',
    REFRESH_FAILED: 'AUTH.REFRESH_FAILED',
    CODE_NOT_VERIFIED: 'AUTH.CODE_NOT_VERIFIED',
    CODE_ALREADY_VERIFIED: 'AUTH.CODE_ALREADY_VERIFIED',
    SIGNUP_FAILED: 'AUTH.SIGNUP_FAILED',
    UNAUTHORIZED: 'AUTH.UNAUTHORIZED',
    RESET_SESSION_NOT_FOUND: 'AUTH.RESET_SESSION_NOT_FOUND',
    RESET_ATTEMPT_ACTIVE: 'AUTH.RESET_ATTEMPT_ACTIVE',
    REGISTRATION_EXPIRED: 'AUTH.REGISTRATION_EXPIRED',
    AUTHORIZATION_EXPIRED: 'AUTH.AUTHORIZATION_EXPIRED',
    RESET_SESSION_EXPIRED: 'AUTH.RESET_SESSION_EXPIRED',
    RESEND_RATE_LIMIT: 'AUTH.RESEND_RATE_LIMIT',
    MAX_ATTEMPTS_REACHED: 'AUTH.MAX_ATTEMPTS_REACHED',
    SIGNIN_FAILED: 'AUTH.SIGNIN_FAILED',
    SESSION_CREATION_FAILED: 'AUTH.SESSION_CREATION_FAILED',
    RESET_PASSWORD_FAILED: 'AUTH.RESET_PASSWORD_FAILED',
    DATA_CORRUPTION: 'DATA_CORRUPTION',
} as const;

export type AuthErrorCode = (typeof AuthErrorCodes)[keyof typeof AuthErrorCodes];

export const AuthErrorMessages: Record<AuthErrorCode, string> = {
    [AuthErrorCodes.DATA_CORRUPTION]: 'Ошибка целостности данных. Попробуйте начать заново',
    [AuthErrorCodes.INVALID_CREDENTIALS]: 'Неверный email или пароль',
    [AuthErrorCodes.INVALID_CODE]: 'Неверный или истекший код подтверждения',
    [AuthErrorCodes.CODE_ALREADY_SENT]: 'Код уже был отправлен. Проверьте почту или подождите',
    [AuthErrorCodes.SESSION_EXPIRED]: 'Сессия истекла. Выполните вход заново',
    [AuthErrorCodes.SIGNOUT_FAILED]: 'Не удалось завершить сессию, попробуйте позже',
    [AuthErrorCodes.TOKEN_INVALID]: 'Недействительный токен обновления',
    [AuthErrorCodes.REFRESH_FAILED]: 'Не удалось обновить токены. Попробуйте позже',
    [AuthErrorCodes.SESSION_NOT_FOUND]: 'Сессия не найдена',
    [AuthErrorCodes.SESSION_REVOKED]: 'Сессия была отозвана. Выполните вход заново',
    [AuthErrorCodes.STRATEGY_NOT_FOUND]: 'Неизвестный контекст операции',
    [AuthErrorCodes.CODE_NOT_VERIFIED]: 'Код подтверждения еще не был верифицирован',
    [AuthErrorCodes.CODE_ALREADY_VERIFIED]: 'Код подтверждения уже верифицирован',
    [AuthErrorCodes.UNAUTHORIZED]: 'Необходимо выполнить вход',
    [AuthErrorCodes.RESET_SESSION_NOT_FOUND]: 'Запрос на сброс пароля не найден',
    [AuthErrorCodes.REGISTRATION_EXPIRED]: 'Код регестрации истек. Зарегистрируйтесь заново',
    [AuthErrorCodes.AUTHORIZATION_EXPIRED]: 'Код авторизации истек. Авторизируйтесь заново',
    [AuthErrorCodes.RESET_SESSION_EXPIRED]: 'Время подтверждения истекло. Запросите код снова',
    [AuthErrorCodes.RESEND_RATE_LIMIT]: 'Слишком частые попытки. Повторная отправка доступна через',
    [AuthErrorCodes.MAX_ATTEMPTS_REACHED]:
        'Превышено максимальное количество попыток. Начните процесс заново',
    [AuthErrorCodes.SIGNIN_FAILED]: 'Не удалось выполнить вход. Попробуйте позже',
    [AuthErrorCodes.SIGNUP_FAILED]: 'Не удалось зарегистрироваться. Попробуйте позже',
    [AuthErrorCodes.SESSION_CREATION_FAILED]: 'Не удалось создать сессию',
    [AuthErrorCodes.RESET_ATTEMPT_ACTIVE]: 'Запрос на сброс пароля уже активен. Проверьте почту',
    [AuthErrorCodes.RESET_PASSWORD_FAILED]: 'Не удалось сбросить пароль. Попробуйте позже',
};
